# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "e2e-github-actions" ]
  pull_request:
    branches: [ "e2e-github-actions" ]

jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'npm'
    - run: npm ci
    - name: Start React app in the background
      run: npm start &
    - name: Run cypress
      run: npm run cypress:e2e
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: newman-report-html
        path: cypress/reports/
        retention-days: 15